active_profile: parhelion
profiles:
  default:
    name: Default
    description: Default project profile using the standard documents folder
    documents_folders:
    - /app/documents
    database: rag_db
    collection_documents: documents
    collection_chunks: chunks
    vector_index: vector_index
    text_index: text_index
  parhelion:
    name: Parhelion Energy
    description: Parhelion Energy knowledge base
    documents_folders:
    - /app/mounts/parhelion-energy
    database: rag_parhelion
    collection_documents: documents
    collection_chunks: chunks
    vector_index: vector_index
    text_index: text_index
  parhelion-full:
    name: Manu-Primary-GDrive
    description: Parhelion Energy knowledge base with Google Drive documents
    documents_folders:
    - /app/mounts/gdrive-root
    database: gdrive-behova-root
    collection_documents: documents
    collection_chunks: chunks
    vector_index: vector_index
    text_index: text_index
