import { TenantConfig } from '../types'

export const quellexConfig: TenantConfig = {
  id: 'quellex',
  branding: {
    appName: 'Quellex',
    tagline: 'Ihr Kanzleiwissen. Schnell gefunden.',
    logoUrl: '/tenants/quellex/assets/quellex-logo.png',
    iconUrl: '/tenants/quellex/assets/quellex-q-icon.png',
    faviconUrl: '/tenants/quellex/assets/quellex-q-icon.png',
  },
  theme: {
    colors: {
      primary: {
        DEFAULT: '#C29629',
        50: '#FDF8E8',
        100: '#F5E6B8',
        200: '#EDD488',
        300: '#E5C258',
        400: '#DDB028',
        500: '#C49B1A',
        600: '#C29629',
        700: '#8B6508',
        800: '#5E4406',
        900: '#312303',
      },
      secondary: {
        DEFAULT: '#248F8F',
        50: '#E6F5F3',
        100: '#B3E0DA',
        200: '#80CBC2',
        300: '#4DB6AA',
        400: '#26A69A',
        500: '#1B9085',
        600: '#248F8F',
        700: '#155E55',
        800: '#10423C',
        900: '#0A2622',
      },
      accent: {
        DEFAULT: '#248F8F',
        50: '#E6F5F3',
        500: '#248F8F',
        700: '#1B6B6B',
      },
      surface: {
        DEFAULT: '#F8F6F2',
        variant: '#EFECE7',
      },
      background: {
        DEFAULT: '#F8F6F2',
        dark: '#0A1629',
      },
      gradient: {
        from: '#C29629',
        to: '#248F8F',
      },
    },
    fonts: {
      sans: ['Inter', 'system-ui', 'sans-serif'],
      display: ['Playfair Display', 'Georgia', 'serif'],
    },
    borderRadius: {
      base: '12px',
      button: '12px',
      input: '8px',
    },
    darkMode: {
      background: '#0A1629',
      surface: '#0F1E33',
      text: '#FFFFFF',
    },
  },
  features: {
    showCloudSources: true,
    showEmailConfig: true,
    showProfiles: true,
    showStrategies: true,
    showEmbeddingBenchmark: false,
    showBackups: true,
    showApiDocs: false,
    landingPageVariant: 'quellex',
  },
  content: {
    i18nOverrides: {
      en: {
        'common.appName': 'Quellex',
        'landing.subtitle': 'Your firm\'s knowledge — instantly accessible',
        'landing.welcomeTo': 'Welcome to Quellex',
        'landing.featuresTitle': 'Built for Legal Professionals',
        'landing.featuresSubtitle': 'Quellex brings AI-powered search and retrieval to your case files, contracts, and legal documents.',
        'landing.features.aiSearch.title': 'Legal Research Assistant',
        'landing.features.aiSearch.description': 'Search across case law, contracts, and internal memos with AI that understands legal context and terminology.',
        'landing.features.multiFormat.description': 'Ingest contracts, court filings, PDFs, emails, and scanned documents — all indexed and searchable.',
        'landing.features.conversational.description': 'Ask questions about your cases in natural language and get precise, cited answers from your knowledge base.',
        'landing.ctaTitle': 'Ready to streamline your legal research?',
        'landing.ctaSubtitleGuest': 'Log in to access your firm\'s knowledge base and start finding answers faster.',
        'landing.footerTagline': 'AI-powered legal knowledge management',
        'landing.benefitsTitle': 'Why Leading Firms Choose Quellex',
        'landing.benefitsSubtitle': 'Quellex is designed with legal professionals in mind. Host it on your own infrastructure, maintain full control of your data, and integrate seamlessly with your existing tools.',
        'chatPage.assistantTitle': 'Quellex Assistant',
        'chatPage.emptyStateDesc': 'Ask questions about your documents. I\'ll search through your knowledge base to find relevant information.',
        // Dashboard suggestion prompts (tenant-specific)
        'dashboard.suggestions.summarize': 'Analyze contract',
        'dashboard.suggestions.findDocument': 'Find precedent',
        'dashboard.suggestions.compare': 'Compare clauses',
        'dashboard.suggestions.explain': 'Summarize ruling',
      },
      de: {
        'common.appName': 'Quellex',
        'landing.subtitle': 'Ihr Kanzleiwissen — sofort verfügbar',
        'landing.welcomeTo': 'Willkommen bei Quellex',
        'landing.featuresTitle': 'Entwickelt für Juristen',
        'landing.featuresSubtitle': 'Quellex bringt KI-gestützte Suche und Recherche in Ihre Akten, Verträge und Rechtsdokumente.',
        'landing.features.aiSearch.title': 'Juristischer Rechercheassistent',
        'landing.features.aiSearch.description': 'Durchsuchen Sie Rechtsprechung, Verträge und interne Notizen mit KI, die juristischen Kontext und Fachsprache versteht.',
        'landing.features.multiFormat.description': 'Erfassen Sie Verträge, Schriftsätze, PDFs, E-Mails und gescannte Dokumente — alles indexiert und durchsuchbar.',
        'landing.features.conversational.description': 'Stellen Sie Fragen zu Ihren Fällen in natürlicher Sprache und erhalten Sie präzise, belegte Antworten aus Ihrer Wissensbasis.',
        'landing.ctaTitle': 'Bereit, Ihre juristische Recherche zu optimieren?',
        'landing.ctaSubtitleGuest': 'Melden Sie sich an, um auf das Kanzleiwissen zuzugreifen und schneller Antworten zu finden.',
        'landing.footerTagline': 'KI-gestütztes juristisches Wissensmanagement',
        'landing.benefitsTitle': 'Warum führende Kanzleien Quellex wählen',
        'landing.benefitsSubtitle': 'Quellex wurde für juristische Fachkräfte konzipiert. Hosten Sie auf Ihrer eigenen Infrastruktur, behalten Sie die volle Kontrolle über Ihre Daten und integrieren Sie nahtlos in bestehende Tools.',
        'chatPage.assistantTitle': 'Quellex-Assistent',
        'chatPage.emptyStateDesc': 'Stellen Sie Fragen zu Ihren Dokumenten. Ich durchsuche Ihre Wissensbasis, um relevante Informationen zu finden.',
        // Dashboard suggestion prompts (tenant-specific)
        'dashboard.suggestions.summarize': 'Vertrag analysieren',
        'dashboard.suggestions.findDocument': 'Präzedenzfall finden',
        'dashboard.suggestions.compare': 'Klauseln vergleichen',
        'dashboard.suggestions.explain': 'Urteil zusammenfassen',
      },
    },
  },
}
